# spring配置
spring:
  application:
    # 应用名称
    name: blog-admin
  datasource:
    # 数据库驱动：
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称
    name: blog
    #数据库地址
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    #账号密码
    username: root
    password: a123456
    type: com.alibaba.druid.pool.DruidDataSource

# 服务器配置
server:
  port: 8889

# mybatis-plus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 全局配置
  global-config:
    db-config:
      # 去除的表明前缀
      table-prefix: ms_
      # 驼峰命名法与下划线命名法映射
      table-underline: true
#    mapper.xml扫描路径，注意mapper.xml文件放在resources中时，要与java中mapper.java目录一致
  mapper-locations: classpath:com.aguo.blogapi.mapper.*
